# Generated by Django 5.2.5 on 2025-08-11 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlutterProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المشروع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('package_name', models.CharField(default='com.example.app', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مشروع Flutter',
                'verbose_name_plural': 'مشاريع Flutter',
            },
        ),
        migrations.CreateModel(
            name='PubDevPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('homepage', models.URLField(blank=True)),
                ('documentation', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='HomePage', max_length=100)),
                ('component_type', models.CharField(choices=[('scaffold', 'Scaffold'), ('appbar', 'AppBar'), ('container', 'Container'), ('text', 'Text'), ('button', 'Button'), ('image', 'Image'), ('listview', 'ListView'), ('column', 'Column'), ('row', 'Row')], max_length=50)),
                ('properties', models.JSONField(default=dict)),
                ('order', models.IntegerField(default=0)),
                ('parent_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.pagecomponent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='generator.flutterproject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='generator.flutterproject')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.pubdevpackage')),
            ],
            options={
                'unique_together': {('project', 'package')},
            },
        ),
    ]
