# Generated by Django 5.2.5 on 2025-08-11 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APKBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('apk_file_path', models.CharField(blank=True, max_length=500)),
                ('build_log', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apk_builds', to='generator.flutterproject')),
            ],
            options={
                'verbose_name': 'APK Build',
                'verbose_name_plural': 'APK Builds',
                'ordering': ['-created_at'],
            },
        ),
    ]
