"""
Django settings for flutter_code_gen project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-81-3odk%-w$x@czish44g7+qimhfe@3ztx#0hkyq8gfr96udae'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # إذا كنت تريد API
    'generator',  # اسم التطبيق
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flutter_code_gen.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']

        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flutter_code_gen.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Flutter SDK Path - it exists here!
FLUTTER_SDK_PATH = r'C:\flutter'

# Verify Flutter exists
flutter_exe = os.path.join(FLUTTER_SDK_PATH, 'bin', 'flutter.bat')
if os.path.exists(flutter_exe):
    print(f"✓ Flutter found at {flutter_exe}")
else:
    print(f"✗ Flutter NOT found at {flutter_exe}")

# Android SDK Path
ANDROID_SDK_PATH = r'C:\android-sdk'
ANDROID_CMDLINE_TOOLS = os.path.join(ANDROID_SDK_PATH, 'cmdline-tools', 'latest')

# Java path (update to your Java 17 path)
JAVA_HOME = r'C:\Program Files\Eclipse Adoptium\jdk-21.0.8.9-hotspot'

# Set environment variables
os.environ['FLUTTER_ROOT'] = FLUTTER_SDK_PATH
os.environ['ANDROID_HOME'] = ANDROID_SDK_PATH
os.environ['ANDROID_SDK_ROOT'] = ANDROID_SDK_PATH
os.environ['JAVA_HOME'] = JAVA_HOME

# Build complete PATH
flutter_bin = os.path.join(FLUTTER_SDK_PATH, 'bin')
android_bin = os.path.join(ANDROID_CMDLINE_TOOLS, 'bin')
java_bin = os.path.join(JAVA_HOME, 'bin')

# Add to PATH (put Flutter first)
os.environ['PATH'] = f"{flutter_bin};{android_bin};{java_bin};{os.environ.get('PATH', '')}"

# Build settings
BUILD_TIMEOUT = 6000
USE_MOCK_BUILD = False

# Debug: Print PATH
print(f"PATH configured: {flutter_bin} is in PATH")



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
